/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const getProject = /* GraphQL */ `
  query GetProject($id: ID!) {
    getProject(id: $id) {
      AR
      ARAgent
      ARStatus
      Area
      Actuals
      Analyst
      ApprovedGrossBudget
      CostCenter
      ProfitCenter
      MAOP
      Product
      TaxJurisdiction
      CurrentForecast
      DirectCosts
      IndirectCosts
      InitialPlan
      OpenPOCommitments
      OriginalARAmount
      PersonResponsible
      PersonResponsibleName
      ProjectType
      SystemStatus
      TM1Reference
      TM1InitialDate
      TM1CurrentDate
      TM1CurrentAmount
      TM1NetAmount
      WBSDescription
      WBSElement
      WBSUserStatus
      WFAgent
      WorkType
      ProjectNumber
      Company
      DistrictDivision
      ReimbursementPercentage
      OverheadPercentage
      Client
      Scope
      Line
      FilePath
      OpsVP
      OpsDirector
      OpsManager
      LinePatrol
      CustomUtilityNumber
      WBSSAPStatus
      State
      County
      City
      GPSCoordinates
      Active
      Weekly
      Monthly
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const listProjects = /* GraphQL */ `
  query ListProjects(
    $filter: ModelProjectFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listProjects(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        AR
        ARAgent
        ARStatus
        Area
        Actuals
        Analyst
        ApprovedGrossBudget
        CostCenter
        ProfitCenter
        MAOP
        Product
        TaxJurisdiction
        CurrentForecast
        DirectCosts
        IndirectCosts
        InitialPlan
        OpenPOCommitments
        OriginalARAmount
        PersonResponsible
        PersonResponsibleName
        ProjectType
        SystemStatus
        TM1Reference
        TM1InitialDate
        TM1CurrentDate
        TM1CurrentAmount
        TM1NetAmount
        WBSDescription
        WBSElement
        WBSUserStatus
        WFAgent
        WorkType
        ProjectNumber
        Company
        DistrictDivision
        ReimbursementPercentage
        OverheadPercentage
        Client
        Scope
        Line
        FilePath
        OpsVP
        OpsDirector
        OpsManager
        LinePatrol
        CustomUtilityNumber
        WBSSAPStatus
        State
        County
        City
        GPSCoordinates
        Active
        Weekly
        Monthly
        id
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
  }
`;
export const getCommitment = /* GraphQL */ `
  query GetCommitment($id: ID!) {
    getCommitment(id: $id) {
      Accassgtquantity
      AcctAssignmentCat
      Activity
      ActivityType
      Asset
      BudgetPeriod
      Building
      BusinessArea
      BusinessEntity
      BusinessProcess
      ChangeIndicator
      CharacteristicDescription1
      CharacteristicDescription2
      CharacteristicDescription3
      CharacteristicValue1
      CharacteristicValue2
      CharacteristicValue3
      CollectiveNumber
      Commitmentitem
      ComponentConsumptionHistory
      ContractNumber
      Controlindicator
      ControllingArea
      CorrectionObject
      Correctionitems
      CostCenter
      Counter
      Createdon
      Currency
      DeletionIndicator
      Distribution
      DocumentDate
      DocumentItem
      EarmarkedFunds
      ExtHierarchyCategory
      ExternalSortNumber
      FunctionalArea
      Fund
      FundsCenter
      GLAccount
      GoodsRecipient
      Grant
      HierarchyNumber
      Incomplete
      IssuingStorageLoc
      Item
      ItemCategory
      Itemcategory
      Land
      LeaseOut
      ManagementContract
      Material
      MaterialGroup
      NameofSupplier
      NetOrderValue
      NetPrice
      Network
      Nondeductible
      NoofPositions
      NotifiedQuantity
      OpenTargetQuantity
      Openvalue
      Order
      OrderPriceUnit
      OrderQuantity
      OrderUnit
      Origin
      Outlineagreement
      POhistoryreleasedocumentation
      PSSTGroup
      PSSTGroupingRule
      Packagenumber
      Partner
      Plant
      Priceunit
      Princagreementitem
      ProfitCenter
      ProfitabSegmtNo
      PurchDocCategory
      PurchasingDocType
      PurchasingDocument
      PurchasingGroup
      Purchasinginforec
      Purchorganization
      QtyReleasedtoDate
      QuantityinSKU
      QuotationDeadline
      RealEstateKey
      RecoveryIndicator
      Referencedate
      ReleaseState
      ReleaseStrategy
      Releasedvalue
      Releasegroup
      Releaseindicator
      RentalUnit
      ReqTrackingNumber
      ReqmtPriority
      RequirementSegment
      RequirementUrgency
      Routingnumberforoperations
      SDDocument
      Schedulelinenumber
      SeqNoofAccountAssgt
      ServiceChargeKey
      SettlementUnit
      ShortText
      SmartNumber
      Stilltobedeliveredqty
      Stilltobedeliveredvalue
      Stilltobeinvoicedqty
      Stilltobeinvoicedval
      StockSegment
      Stockkeepingunit
      Storagelocation
      Subnumber
      SupplierSupplyingPlant
      TargValHdr
      TargetQuantity
      TaxCode
      TaxJurisdiction
      Totalopenvalue
      UnloadingPoint
      ValidityPerStart
      ValidityPeriodEnd
      WBSElement
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const listCommitments = /* GraphQL */ `
  query ListCommitments(
    $filter: ModelCommitmentFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listCommitments(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        Accassgtquantity
        AcctAssignmentCat
        Activity
        ActivityType
        Asset
        BudgetPeriod
        Building
        BusinessArea
        BusinessEntity
        BusinessProcess
        ChangeIndicator
        CharacteristicDescription1
        CharacteristicDescription2
        CharacteristicDescription3
        CharacteristicValue1
        CharacteristicValue2
        CharacteristicValue3
        CollectiveNumber
        Commitmentitem
        ComponentConsumptionHistory
        ContractNumber
        Controlindicator
        ControllingArea
        CorrectionObject
        Correctionitems
        CostCenter
        Counter
        Createdon
        Currency
        DeletionIndicator
        Distribution
        DocumentDate
        DocumentItem
        EarmarkedFunds
        ExtHierarchyCategory
        ExternalSortNumber
        FunctionalArea
        Fund
        FundsCenter
        GLAccount
        GoodsRecipient
        Grant
        HierarchyNumber
        Incomplete
        IssuingStorageLoc
        Item
        ItemCategory
        Itemcategory
        Land
        LeaseOut
        ManagementContract
        Material
        MaterialGroup
        NameofSupplier
        NetOrderValue
        NetPrice
        Network
        Nondeductible
        NoofPositions
        NotifiedQuantity
        OpenTargetQuantity
        Openvalue
        Order
        OrderPriceUnit
        OrderQuantity
        OrderUnit
        Origin
        Outlineagreement
        POhistoryreleasedocumentation
        PSSTGroup
        PSSTGroupingRule
        Packagenumber
        Partner
        Plant
        Priceunit
        Princagreementitem
        ProfitCenter
        ProfitabSegmtNo
        PurchDocCategory
        PurchasingDocType
        PurchasingDocument
        PurchasingGroup
        Purchasinginforec
        Purchorganization
        QtyReleasedtoDate
        QuantityinSKU
        QuotationDeadline
        RealEstateKey
        RecoveryIndicator
        Referencedate
        ReleaseState
        ReleaseStrategy
        Releasedvalue
        Releasegroup
        Releaseindicator
        RentalUnit
        ReqTrackingNumber
        ReqmtPriority
        RequirementSegment
        RequirementUrgency
        Routingnumberforoperations
        SDDocument
        Schedulelinenumber
        SeqNoofAccountAssgt
        ServiceChargeKey
        SettlementUnit
        ShortText
        SmartNumber
        Stilltobedeliveredqty
        Stilltobedeliveredvalue
        Stilltobeinvoicedqty
        Stilltobeinvoicedval
        StockSegment
        Stockkeepingunit
        Storagelocation
        Subnumber
        SupplierSupplyingPlant
        TargValHdr
        TargetQuantity
        TaxCode
        TaxJurisdiction
        Totalopenvalue
        UnloadingPoint
        ValidityPerStart
        ValidityPeriodEnd
        WBSElement
        WBSelement
        WBSID
        id
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
  }
`;
export const getTransaction = /* GraphQL */ `
  query GetTransaction($id: ID!) {
    getTransaction(id: $id) {
      Asset
      BusinessTransaction
      COObjectName
      COPartnerObjectName
      COareacurrency
      CompanyCode
      CostElement
      Costelementdescr
      Costelementname
      Createdon
      DebitType
      DocumentDate
      DocumentHeaderText
      DocumentNumber
      DocumentType
      DrCrindicator
      ExchangeRateType
      FIPostingItem
      FiscalYear
      FromPeriod
      Item
      Ledger
      LogicalSystem
      Logsystemsource
      Material
      MaterialDescription
      MaterialGroup
      Name
      Nameofoffsettingaccount
      Object
      ObjectCurrency
      ObjectType
      OffsettingAccount
      OffsettingAccountType
      OriginalBusTrans
      PartnerCoCode
      PartnerObject
      PartnerObjectClass
      PartnerObjectType
      Partnerobjecttype
      Partnerorderno
      Period
      Plant
      Postedunitofmeas
      PostingDate
      PostingRow
      Projectdefinition
      PurchaseOrderText
      PurchasingDocument
      RefCompanyCode
      RefDocumentType
      RefFiscalYear
      Refdocumentnumber
      Reference
      ReferenceKey
      ReferenceOrgUnit
      Referenceprocedure
      ReportCurrency
      Respcostcntr
      ReversalOrganizatns
      ReversalRefNo
      Reversaldocument
      Reversed
      Rowinopversion
      Supplier
      TaxJurisdiction
      Timecreated
      TimeofEntry
      ToPeriod
      Totalquantity
      TradingPartnerNo
      TransactionCurrency
      UserName
      ValCOAreaCrcy
      Valinrepcur
      ValueDate
      ValueTranCurr
      ValueType
      ValueinObjCrcy
      Varvalinrepcur
      VblValCOCrcy
      VblvalueObjcurr
      VblvalueTranCurr
      VendorName
      Version
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const listTransactions = /* GraphQL */ `
  query ListTransactions(
    $filter: ModelTransactionFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listTransactions(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        Asset
        BusinessTransaction
        COObjectName
        COPartnerObjectName
        COareacurrency
        CompanyCode
        CostElement
        Costelementdescr
        Costelementname
        Createdon
        DebitType
        DocumentDate
        DocumentHeaderText
        DocumentNumber
        DocumentType
        DrCrindicator
        ExchangeRateType
        FIPostingItem
        FiscalYear
        FromPeriod
        Item
        Ledger
        LogicalSystem
        Logsystemsource
        Material
        MaterialDescription
        MaterialGroup
        Name
        Nameofoffsettingaccount
        Object
        ObjectCurrency
        ObjectType
        OffsettingAccount
        OffsettingAccountType
        OriginalBusTrans
        PartnerCoCode
        PartnerObject
        PartnerObjectClass
        PartnerObjectType
        Partnerobjecttype
        Partnerorderno
        Period
        Plant
        Postedunitofmeas
        PostingDate
        PostingRow
        Projectdefinition
        PurchaseOrderText
        PurchasingDocument
        RefCompanyCode
        RefDocumentType
        RefFiscalYear
        Refdocumentnumber
        Reference
        ReferenceKey
        ReferenceOrgUnit
        Referenceprocedure
        ReportCurrency
        Respcostcntr
        ReversalOrganizatns
        ReversalRefNo
        Reversaldocument
        Reversed
        Rowinopversion
        Supplier
        TaxJurisdiction
        Timecreated
        TimeofEntry
        ToPeriod
        Totalquantity
        TradingPartnerNo
        TransactionCurrency
        UserName
        ValCOAreaCrcy
        Valinrepcur
        ValueDate
        ValueTranCurr
        ValueType
        ValueinObjCrcy
        Varvalinrepcur
        VblValCOCrcy
        VblvalueObjcurr
        VblvalueTranCurr
        VendorName
        Version
        WBSelement
        WBSID
        id
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
  }
`;
export const getProjectManagerNotes = /* GraphQL */ `
  query GetProjectManagerNotes($id: ID!) {
    getProjectManagerNotes(id: $id) {
      WBS
      Date
      User
      Category
      Comment
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const listProjectManagerNotes = /* GraphQL */ `
  query ListProjectManagerNotes(
    $filter: ModelProjectManagerNotesFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listProjectManagerNotes(
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        WBS
        Date
        User
        Category
        Comment
        WBSID
        id
        createdAt
        updatedAt
        __typename
      }
      nextToken
      __typename
    }
  }
`;
