/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateProject = /* GraphQL */ `
  subscription OnCreateProject($filter: ModelSubscriptionProjectFilterInput) {
    onCreateProject(filter: $filter) {
      AR
      ARAgent
      ARStatus
      Area
      Actuals
      Analyst
      ApprovedGrossBudget
      CostCenter
      ProfitCenter
      MAOP
      Product
      TaxJurisdiction
      CurrentForecast
      DirectCosts
      IndirectCosts
      InitialPlan
      OpenPOCommitments
      OriginalARAmount
      PersonResponsible
      PersonResponsibleName
      ProjectType
      SystemStatus
      TM1Reference
      TM1InitialDate
      TM1CurrentDate
      TM1CurrentAmount
      TM1NetAmount
      WBSDescription
      WBSElement
      WBSUserStatus
      WFAgent
      WorkType
      ProjectNumber
      Company
      DistrictDivision
      ReimbursementPercentage
      OverheadPercentage
      Client
      Scope
      Line
      FilePath
      OpsVP
      OpsDirector
      OpsManager
      LinePatrol
      CustomUtilityNumber
      WBSSAPStatus
      State
      County
      City
      GPSCoordinates
      Active
      Weekly
      Monthly
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateProject = /* GraphQL */ `
  subscription OnUpdateProject($filter: ModelSubscriptionProjectFilterInput) {
    onUpdateProject(filter: $filter) {
      AR
      ARAgent
      ARStatus
      Area
      Actuals
      Analyst
      ApprovedGrossBudget
      CostCenter
      ProfitCenter
      MAOP
      Product
      TaxJurisdiction
      CurrentForecast
      DirectCosts
      IndirectCosts
      InitialPlan
      OpenPOCommitments
      OriginalARAmount
      PersonResponsible
      PersonResponsibleName
      ProjectType
      SystemStatus
      TM1Reference
      TM1InitialDate
      TM1CurrentDate
      TM1CurrentAmount
      TM1NetAmount
      WBSDescription
      WBSElement
      WBSUserStatus
      WFAgent
      WorkType
      ProjectNumber
      Company
      DistrictDivision
      ReimbursementPercentage
      OverheadPercentage
      Client
      Scope
      Line
      FilePath
      OpsVP
      OpsDirector
      OpsManager
      LinePatrol
      CustomUtilityNumber
      WBSSAPStatus
      State
      County
      City
      GPSCoordinates
      Active
      Weekly
      Monthly
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteProject = /* GraphQL */ `
  subscription OnDeleteProject($filter: ModelSubscriptionProjectFilterInput) {
    onDeleteProject(filter: $filter) {
      AR
      ARAgent
      ARStatus
      Area
      Actuals
      Analyst
      ApprovedGrossBudget
      CostCenter
      ProfitCenter
      MAOP
      Product
      TaxJurisdiction
      CurrentForecast
      DirectCosts
      IndirectCosts
      InitialPlan
      OpenPOCommitments
      OriginalARAmount
      PersonResponsible
      PersonResponsibleName
      ProjectType
      SystemStatus
      TM1Reference
      TM1InitialDate
      TM1CurrentDate
      TM1CurrentAmount
      TM1NetAmount
      WBSDescription
      WBSElement
      WBSUserStatus
      WFAgent
      WorkType
      ProjectNumber
      Company
      DistrictDivision
      ReimbursementPercentage
      OverheadPercentage
      Client
      Scope
      Line
      FilePath
      OpsVP
      OpsDirector
      OpsManager
      LinePatrol
      CustomUtilityNumber
      WBSSAPStatus
      State
      County
      City
      GPSCoordinates
      Active
      Weekly
      Monthly
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateCommitment = /* GraphQL */ `
  subscription OnCreateCommitment(
    $filter: ModelSubscriptionCommitmentFilterInput
  ) {
    onCreateCommitment(filter: $filter) {
      Accassgtquantity
      AcctAssignmentCat
      Activity
      ActivityType
      Asset
      BudgetPeriod
      Building
      BusinessArea
      BusinessEntity
      BusinessProcess
      ChangeIndicator
      CharacteristicDescription1
      CharacteristicDescription2
      CharacteristicDescription3
      CharacteristicValue1
      CharacteristicValue2
      CharacteristicValue3
      CollectiveNumber
      Commitmentitem
      ComponentConsumptionHistory
      ContractNumber
      Controlindicator
      ControllingArea
      CorrectionObject
      Correctionitems
      CostCenter
      Counter
      Createdon
      Currency
      DeletionIndicator
      Distribution
      DocumentDate
      DocumentItem
      EarmarkedFunds
      ExtHierarchyCategory
      ExternalSortNumber
      FunctionalArea
      Fund
      FundsCenter
      GLAccount
      GoodsRecipient
      Grant
      HierarchyNumber
      Incomplete
      IssuingStorageLoc
      Item
      ItemCategory
      Itemcategory
      Land
      LeaseOut
      ManagementContract
      Material
      MaterialGroup
      NameofSupplier
      NetOrderValue
      NetPrice
      Network
      Nondeductible
      NoofPositions
      NotifiedQuantity
      OpenTargetQuantity
      Openvalue
      Order
      OrderPriceUnit
      OrderQuantity
      OrderUnit
      Origin
      Outlineagreement
      POhistoryreleasedocumentation
      PSSTGroup
      PSSTGroupingRule
      Packagenumber
      Partner
      Plant
      Priceunit
      Princagreementitem
      ProfitCenter
      ProfitabSegmtNo
      PurchDocCategory
      PurchasingDocType
      PurchasingDocument
      PurchasingGroup
      Purchasinginforec
      Purchorganization
      QtyReleasedtoDate
      QuantityinSKU
      QuotationDeadline
      RealEstateKey
      RecoveryIndicator
      Referencedate
      ReleaseState
      ReleaseStrategy
      Releasedvalue
      Releasegroup
      Releaseindicator
      RentalUnit
      ReqTrackingNumber
      ReqmtPriority
      RequirementSegment
      RequirementUrgency
      Routingnumberforoperations
      SDDocument
      Schedulelinenumber
      SeqNoofAccountAssgt
      ServiceChargeKey
      SettlementUnit
      ShortText
      SmartNumber
      Stilltobedeliveredqty
      Stilltobedeliveredvalue
      Stilltobeinvoicedqty
      Stilltobeinvoicedval
      StockSegment
      Stockkeepingunit
      Storagelocation
      Subnumber
      SupplierSupplyingPlant
      TargValHdr
      TargetQuantity
      TaxCode
      TaxJurisdiction
      Totalopenvalue
      UnloadingPoint
      ValidityPerStart
      ValidityPeriodEnd
      WBSElement
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateCommitment = /* GraphQL */ `
  subscription OnUpdateCommitment(
    $filter: ModelSubscriptionCommitmentFilterInput
  ) {
    onUpdateCommitment(filter: $filter) {
      Accassgtquantity
      AcctAssignmentCat
      Activity
      ActivityType
      Asset
      BudgetPeriod
      Building
      BusinessArea
      BusinessEntity
      BusinessProcess
      ChangeIndicator
      CharacteristicDescription1
      CharacteristicDescription2
      CharacteristicDescription3
      CharacteristicValue1
      CharacteristicValue2
      CharacteristicValue3
      CollectiveNumber
      Commitmentitem
      ComponentConsumptionHistory
      ContractNumber
      Controlindicator
      ControllingArea
      CorrectionObject
      Correctionitems
      CostCenter
      Counter
      Createdon
      Currency
      DeletionIndicator
      Distribution
      DocumentDate
      DocumentItem
      EarmarkedFunds
      ExtHierarchyCategory
      ExternalSortNumber
      FunctionalArea
      Fund
      FundsCenter
      GLAccount
      GoodsRecipient
      Grant
      HierarchyNumber
      Incomplete
      IssuingStorageLoc
      Item
      ItemCategory
      Itemcategory
      Land
      LeaseOut
      ManagementContract
      Material
      MaterialGroup
      NameofSupplier
      NetOrderValue
      NetPrice
      Network
      Nondeductible
      NoofPositions
      NotifiedQuantity
      OpenTargetQuantity
      Openvalue
      Order
      OrderPriceUnit
      OrderQuantity
      OrderUnit
      Origin
      Outlineagreement
      POhistoryreleasedocumentation
      PSSTGroup
      PSSTGroupingRule
      Packagenumber
      Partner
      Plant
      Priceunit
      Princagreementitem
      ProfitCenter
      ProfitabSegmtNo
      PurchDocCategory
      PurchasingDocType
      PurchasingDocument
      PurchasingGroup
      Purchasinginforec
      Purchorganization
      QtyReleasedtoDate
      QuantityinSKU
      QuotationDeadline
      RealEstateKey
      RecoveryIndicator
      Referencedate
      ReleaseState
      ReleaseStrategy
      Releasedvalue
      Releasegroup
      Releaseindicator
      RentalUnit
      ReqTrackingNumber
      ReqmtPriority
      RequirementSegment
      RequirementUrgency
      Routingnumberforoperations
      SDDocument
      Schedulelinenumber
      SeqNoofAccountAssgt
      ServiceChargeKey
      SettlementUnit
      ShortText
      SmartNumber
      Stilltobedeliveredqty
      Stilltobedeliveredvalue
      Stilltobeinvoicedqty
      Stilltobeinvoicedval
      StockSegment
      Stockkeepingunit
      Storagelocation
      Subnumber
      SupplierSupplyingPlant
      TargValHdr
      TargetQuantity
      TaxCode
      TaxJurisdiction
      Totalopenvalue
      UnloadingPoint
      ValidityPerStart
      ValidityPeriodEnd
      WBSElement
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteCommitment = /* GraphQL */ `
  subscription OnDeleteCommitment(
    $filter: ModelSubscriptionCommitmentFilterInput
  ) {
    onDeleteCommitment(filter: $filter) {
      Accassgtquantity
      AcctAssignmentCat
      Activity
      ActivityType
      Asset
      BudgetPeriod
      Building
      BusinessArea
      BusinessEntity
      BusinessProcess
      ChangeIndicator
      CharacteristicDescription1
      CharacteristicDescription2
      CharacteristicDescription3
      CharacteristicValue1
      CharacteristicValue2
      CharacteristicValue3
      CollectiveNumber
      Commitmentitem
      ComponentConsumptionHistory
      ContractNumber
      Controlindicator
      ControllingArea
      CorrectionObject
      Correctionitems
      CostCenter
      Counter
      Createdon
      Currency
      DeletionIndicator
      Distribution
      DocumentDate
      DocumentItem
      EarmarkedFunds
      ExtHierarchyCategory
      ExternalSortNumber
      FunctionalArea
      Fund
      FundsCenter
      GLAccount
      GoodsRecipient
      Grant
      HierarchyNumber
      Incomplete
      IssuingStorageLoc
      Item
      ItemCategory
      Itemcategory
      Land
      LeaseOut
      ManagementContract
      Material
      MaterialGroup
      NameofSupplier
      NetOrderValue
      NetPrice
      Network
      Nondeductible
      NoofPositions
      NotifiedQuantity
      OpenTargetQuantity
      Openvalue
      Order
      OrderPriceUnit
      OrderQuantity
      OrderUnit
      Origin
      Outlineagreement
      POhistoryreleasedocumentation
      PSSTGroup
      PSSTGroupingRule
      Packagenumber
      Partner
      Plant
      Priceunit
      Princagreementitem
      ProfitCenter
      ProfitabSegmtNo
      PurchDocCategory
      PurchasingDocType
      PurchasingDocument
      PurchasingGroup
      Purchasinginforec
      Purchorganization
      QtyReleasedtoDate
      QuantityinSKU
      QuotationDeadline
      RealEstateKey
      RecoveryIndicator
      Referencedate
      ReleaseState
      ReleaseStrategy
      Releasedvalue
      Releasegroup
      Releaseindicator
      RentalUnit
      ReqTrackingNumber
      ReqmtPriority
      RequirementSegment
      RequirementUrgency
      Routingnumberforoperations
      SDDocument
      Schedulelinenumber
      SeqNoofAccountAssgt
      ServiceChargeKey
      SettlementUnit
      ShortText
      SmartNumber
      Stilltobedeliveredqty
      Stilltobedeliveredvalue
      Stilltobeinvoicedqty
      Stilltobeinvoicedval
      StockSegment
      Stockkeepingunit
      Storagelocation
      Subnumber
      SupplierSupplyingPlant
      TargValHdr
      TargetQuantity
      TaxCode
      TaxJurisdiction
      Totalopenvalue
      UnloadingPoint
      ValidityPerStart
      ValidityPeriodEnd
      WBSElement
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateTransaction = /* GraphQL */ `
  subscription OnCreateTransaction(
    $filter: ModelSubscriptionTransactionFilterInput
  ) {
    onCreateTransaction(filter: $filter) {
      Asset
      BusinessTransaction
      COObjectName
      COPartnerObjectName
      COareacurrency
      CompanyCode
      CostElement
      Costelementdescr
      Costelementname
      Createdon
      DebitType
      DocumentDate
      DocumentHeaderText
      DocumentNumber
      DocumentType
      DrCrindicator
      ExchangeRateType
      FIPostingItem
      FiscalYear
      FromPeriod
      Item
      Ledger
      LogicalSystem
      Logsystemsource
      Material
      MaterialDescription
      MaterialGroup
      Name
      Nameofoffsettingaccount
      Object
      ObjectCurrency
      ObjectType
      OffsettingAccount
      OffsettingAccountType
      OriginalBusTrans
      PartnerCoCode
      PartnerObject
      PartnerObjectClass
      PartnerObjectType
      Partnerobjecttype
      Partnerorderno
      Period
      Plant
      Postedunitofmeas
      PostingDate
      PostingRow
      Projectdefinition
      PurchaseOrderText
      PurchasingDocument
      RefCompanyCode
      RefDocumentType
      RefFiscalYear
      Refdocumentnumber
      Reference
      ReferenceKey
      ReferenceOrgUnit
      Referenceprocedure
      ReportCurrency
      Respcostcntr
      ReversalOrganizatns
      ReversalRefNo
      Reversaldocument
      Reversed
      Rowinopversion
      Supplier
      TaxJurisdiction
      Timecreated
      TimeofEntry
      ToPeriod
      Totalquantity
      TradingPartnerNo
      TransactionCurrency
      UserName
      ValCOAreaCrcy
      Valinrepcur
      ValueDate
      ValueTranCurr
      ValueType
      ValueinObjCrcy
      Varvalinrepcur
      VblValCOCrcy
      VblvalueObjcurr
      VblvalueTranCurr
      VendorName
      Version
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateTransaction = /* GraphQL */ `
  subscription OnUpdateTransaction(
    $filter: ModelSubscriptionTransactionFilterInput
  ) {
    onUpdateTransaction(filter: $filter) {
      Asset
      BusinessTransaction
      COObjectName
      COPartnerObjectName
      COareacurrency
      CompanyCode
      CostElement
      Costelementdescr
      Costelementname
      Createdon
      DebitType
      DocumentDate
      DocumentHeaderText
      DocumentNumber
      DocumentType
      DrCrindicator
      ExchangeRateType
      FIPostingItem
      FiscalYear
      FromPeriod
      Item
      Ledger
      LogicalSystem
      Logsystemsource
      Material
      MaterialDescription
      MaterialGroup
      Name
      Nameofoffsettingaccount
      Object
      ObjectCurrency
      ObjectType
      OffsettingAccount
      OffsettingAccountType
      OriginalBusTrans
      PartnerCoCode
      PartnerObject
      PartnerObjectClass
      PartnerObjectType
      Partnerobjecttype
      Partnerorderno
      Period
      Plant
      Postedunitofmeas
      PostingDate
      PostingRow
      Projectdefinition
      PurchaseOrderText
      PurchasingDocument
      RefCompanyCode
      RefDocumentType
      RefFiscalYear
      Refdocumentnumber
      Reference
      ReferenceKey
      ReferenceOrgUnit
      Referenceprocedure
      ReportCurrency
      Respcostcntr
      ReversalOrganizatns
      ReversalRefNo
      Reversaldocument
      Reversed
      Rowinopversion
      Supplier
      TaxJurisdiction
      Timecreated
      TimeofEntry
      ToPeriod
      Totalquantity
      TradingPartnerNo
      TransactionCurrency
      UserName
      ValCOAreaCrcy
      Valinrepcur
      ValueDate
      ValueTranCurr
      ValueType
      ValueinObjCrcy
      Varvalinrepcur
      VblValCOCrcy
      VblvalueObjcurr
      VblvalueTranCurr
      VendorName
      Version
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteTransaction = /* GraphQL */ `
  subscription OnDeleteTransaction(
    $filter: ModelSubscriptionTransactionFilterInput
  ) {
    onDeleteTransaction(filter: $filter) {
      Asset
      BusinessTransaction
      COObjectName
      COPartnerObjectName
      COareacurrency
      CompanyCode
      CostElement
      Costelementdescr
      Costelementname
      Createdon
      DebitType
      DocumentDate
      DocumentHeaderText
      DocumentNumber
      DocumentType
      DrCrindicator
      ExchangeRateType
      FIPostingItem
      FiscalYear
      FromPeriod
      Item
      Ledger
      LogicalSystem
      Logsystemsource
      Material
      MaterialDescription
      MaterialGroup
      Name
      Nameofoffsettingaccount
      Object
      ObjectCurrency
      ObjectType
      OffsettingAccount
      OffsettingAccountType
      OriginalBusTrans
      PartnerCoCode
      PartnerObject
      PartnerObjectClass
      PartnerObjectType
      Partnerobjecttype
      Partnerorderno
      Period
      Plant
      Postedunitofmeas
      PostingDate
      PostingRow
      Projectdefinition
      PurchaseOrderText
      PurchasingDocument
      RefCompanyCode
      RefDocumentType
      RefFiscalYear
      Refdocumentnumber
      Reference
      ReferenceKey
      ReferenceOrgUnit
      Referenceprocedure
      ReportCurrency
      Respcostcntr
      ReversalOrganizatns
      ReversalRefNo
      Reversaldocument
      Reversed
      Rowinopversion
      Supplier
      TaxJurisdiction
      Timecreated
      TimeofEntry
      ToPeriod
      Totalquantity
      TradingPartnerNo
      TransactionCurrency
      UserName
      ValCOAreaCrcy
      Valinrepcur
      ValueDate
      ValueTranCurr
      ValueType
      ValueinObjCrcy
      Varvalinrepcur
      VblValCOCrcy
      VblvalueObjcurr
      VblvalueTranCurr
      VendorName
      Version
      WBSelement
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateProjectManagerNotes = /* GraphQL */ `
  subscription OnCreateProjectManagerNotes(
    $filter: ModelSubscriptionProjectManagerNotesFilterInput
  ) {
    onCreateProjectManagerNotes(filter: $filter) {
      WBS
      Date
      User
      Category
      Comment
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateProjectManagerNotes = /* GraphQL */ `
  subscription OnUpdateProjectManagerNotes(
    $filter: ModelSubscriptionProjectManagerNotesFilterInput
  ) {
    onUpdateProjectManagerNotes(filter: $filter) {
      WBS
      Date
      User
      Category
      Comment
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteProjectManagerNotes = /* GraphQL */ `
  subscription OnDeleteProjectManagerNotes(
    $filter: ModelSubscriptionProjectManagerNotesFilterInput
  ) {
    onDeleteProjectManagerNotes(filter: $filter) {
      WBS
      Date
      User
      Category
      Comment
      WBSID
      id
      createdAt
      updatedAt
      __typename
    }
  }
`;
